# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50, unique=True)),
                ('info', models.CharField(max_length=1500)),
                ('districts', models.ManyToManyField(to='kiev_map.District')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ism_id', models.CharField(max_length=20, unique=True)),
                ('info', models.TextField()),
                ('districts', models.ManyToManyField(to='kiev_map.District')),
            ],
            options={
                'verbose_name_plural': 'Streets',
            },
        ),
        migrations.AddField(
            model_name='photos',
            name='streets',
            field=models.ManyToManyField(blank=True, to='kiev_map.Street'),
        ),
    ]
