# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiev_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='shortIntro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photos',
            name='file',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='street',
            name='shortIntro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
