# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiev_map', '0003_auto_20181202_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answers', models.TextField()),
                ('correct_answer', models.CharField(max_length=10)),
            ],
        ),
    ]
